# Auto-generated remaining name translations for poe2 passive tree
REMAINING_NAMES = {
    'A Solid Plan': '稳妥计策',
    'Abasement': '屈辱',
    'Acceleration': '加速',
    'Accuracy': '命中',
    'Acolyte of Chayula': '查尤拉之追随者',
    'Adaptable Assault': '灵活突袭',
    'Adaptive Capability': '适应能力',
    'Advanced Munitions': '高级弹药',
    'Advanced Thaumaturgy': '高等奇术',
    'Affliction Enforcer': '苦难执行者',
    'Aftershocks': '余震',
    'Against the Elements': '对抗元素',
    'Aggravation': '加剧',
    'Agile Sprinter': '敏捷冲刺者',
    'Agonising Calamity': '痛苦灾厄',
    'Alchemical Oil': '炼金油',
    'Altered Brain Chemistry': '脑化学改变',
    'Alternating Current': '交流电',
    'Amazon': '亚马逊',
    'Among the Hordes': '群敌之中',
    'Anger Management': '怒气管理',
    'Anticipation': '预判',
    'Apex of the Moment': '时刻之巅',
    'Apocalypse': '天启',
    'Arsonist': '纵火犯',
    'As the Whispers Demand': '如低语所愿',
    'Asceticism': '禁欲主义',
    'Aspiring Genius': '有志天才',
    'Authority': '权威',
    'Avidity': '贪婪',
    'Azmeri Brew': '阿兹梅里酿造',
    'Back in Action': '重返战场',
    'Backstabbing': '背刺',
    'Bannerman': '旗手',
    'Barrier of Venarius': '维纳留斯之障',
    'Barya of Kelari': '克拉里之币',
    'Barya of Navira': '纳维拉之币',
    'Barya of Ruzhan': '鲁赞之币',
    'Baryanic Leylines': '巴里亚尼地脉',
    'Bashing Beast': '猛击野兽',
    'Battle Trance': '战斗恍惚',
    'Battle-hardened': '久经沙场',
    'Beastial Skin': '野兽之皮',
    'Beef': '筋肉',
    'Behemoth': '巨兽',
    "Beidat's Gaze": '贝达特之凝视',
    "Beidat's Will": '贝达特之意志',
    'Blackened Heart': '黑化之心',
    'Blackflame Covenant': '黑焰契约',
    'Blade Catcher': '接刃者',
    'Blade Flurry': '刀刃乱舞',
    'Blazing Arms': '炽热之臂',
    'Blessing of the Moon': '月之祝福',
    'Bloodletting': '放血',
    'Bloodthirsty': '嗜血',
    'Blur': '模糊',
    'Blurred Motion': '模糊动作',
    'Bolstering Implants': '强化植入体',
    'Bolstering Yell': '振奋呐喊',
    'Bond of the Ape': '猿之羁绊',
    'Bond of the Cat': '猫之羁绊',
    'Bond of the Mamba': '曼巴之羁绊',
    'Bond of the Owl': '枭之羁绊',
    'Bond of the Viper': '蝰蛇之羁绊',
    'Bonded Precision': '羁绊精准',
    'Boon of the Beast': '野兽之恩赐',
    'Bounty Hunter': '赏金猎人',
    'Branching Bolts': '分支弩矢',
    'Bravado': '虚张声势',
    'Breakage': '破损',
    'Breaking Blows': '破防打击',
    'Breaking Point': '临界点',
    'Breath of Ice': '冰之吐息',
    'Brinerot Ferocity': '海腐残暴',
    'Bringer of Order': '秩序使者',
    'Briny Carapace': '咸水甲壳',
    'Brush Off': '弹开',
    'Bullseye': '正中靶心',
    'Bulwark': '壁垒',
    'Burn Away': '燃尽',
    'Burnout': '燃尽',
    'Cacophony': '嘈杂',
    'Called Shots': '精准射击',
    'Cannons, Ready!': '火炮就绪！',
    'Captivating Companionship': '迷人同伴',
    'Careful Aim': '谨慎瞄准',
    'Careful Assassin': '谨慎刺客',
    'Careful Consideration': '深思熟虑',
    'Casting Cascade': '施法连瀑',
    'Catalysis': '催化',
    'Catlike Agility': '如猫敏捷',
    'Cautious Concoctions': '谨慎合剂',
    'Ceremonial Ablution': '仪式沐浴',
    "Chayula's Gift": '查尤拉之赠礼',
    'Chillproof': '防冰缓',
    'Chronomancer': '时空术士',
    'Chronomancy': '时空魔法',
    'Close Confines': '逼仄空间',
    'Cluster Bombs': '集束炸弹',
    'Coated Arms': '涂毒武器',
    'Coated Knife': '涂毒匕首',
    'Combat Alchemy': '战斗炼金',
    'Coming Calamity': '即将到来的灾厄',
    'Comradery': '同志情谊',
    'Conall the Hunted': '被猎者康纳尔',
    'Conductive Embrace': '导电拥抱',
    'Conservative Casting': '保守施法',
    'Consistent Intake': '持续摄入',
    'Constricting': '收缩',
    'Convalescence': '康复',
    'Cooked': '煮熟',
    'Corpses': '尸体',
    'Corruption Endures': '腐化永存',
    'Counterstancing': '反击姿态',
    'Cower Before the First Ones': '在先民面前畏缩',
    'Crashing Wave': '冲击波',
    'Cremating Cries': '火葬之嚎',
    'Cremation': '火化',
    'Crimson Assault': '猩红突袭',
    'Cruel Fate': '残酷命运',
    'Crushing Judgement': '粉碎审判',
    'Crushing Verdict': '粉碎判决',
    'Crystalline Phylactery': '水晶命匣',
    'Crystallised Immunities': '结晶免疫',
    'Cull the Hordes': '清除群敌',
    'DUELIST': '决斗者',
    'Dance with Death': '与死亡共舞',
    'Dangerous Blossom': '危险绽放',
    'Darkness': '黑暗',
    'Dazing Blocks': '眩晕格挡',
    'Dead can Dance': '死者能舞',
    'Deadeye': '锐眼',
    'Deafening Cries': '震耳嚎叫',
    'Death from Afar': '远程击杀',
    'Decisive Retreat': '果断撤退',
    'Deepening Shadows': '加深暗影',
    "Defender's Resolve": '守护者之决心',
    'Defensive Reflexes': '防御反射',
    'Delayed Danger': '延迟危险',
    'Demolitionist': '爆破专家',
    'Demonic Possession': '恶魔附身',
    'Desperate Times': '绝望时刻',
    'Destructive Apparatus': '毁灭装置',
    'Determined Precision': '坚定精准',
    'Devastation': '毁灭',
    'Devestating Devices': '毁灭装置',
    'Devoted Protector': '忠诚守护者',
    'Dimensional Weakspot': '维度弱点',
    'Direct Approach': '直接手段',
    'Disciple of Varashta': '瓦拉斯塔信徒',
    'Disorientation': '迷乱',
    'Dispatch Foes': '消灭敌人',
    'Distant Dreamer': '远方的梦想家',
    'Distracted Target': '分心目标',
    'Dizzying Sweep': '眩晕横扫',
    "Dominus' Providence": '多米努斯之天佑',
    'Draiocht Cleansing': '德莱奥赫特净化',
    'Dreamcatcher': '捕梦网',
    'Drenched': '浸透',
    'Dynamism': '活力',
    'Eagle Eye': '鹰眼',
    'Easy Going': '随和',
    'Easy Target': '易中目标',
    'Echoing Flames': '回响烈焰',
    'Echoing Pulse': '回响脉冲',
    'Effervescent': '沸腾',
    'Efficient Alchemy': '高效炼金',
    'Efficient Casting': '高效施法',
    'Efficient Contraptions': '高效装置',
    'Efficient Inscriptions': '高效铭文',
    'Efficient Killing': '高效击杀',
    'Efficient Loading': '高效装填',
    'Electric Amplification': '电力放大',
    'Electrotherapy': '电疗',
    'Embodiment of Death': '死亡化身',
    'Emboldened Avatar': '鼓舞化身',
    'Emboldening Casts': '鼓舞施法',
    'Emboldening Lead': '鼓舞领导',
    'Embrace the Darkness': '拥抱黑暗',
    'Encompassing Domain': '包容领域',
    'Endlessly Soaring': '无尽翱翔',
    'Endured Suffering': '忍受的苦难',
    'Energise': '充能',
    'Engineered Blaze': '工程烈焰',
    'Enhanced Barrier': '强化屏障',
    'Enhanced Effectiveness': '强化效能',
    'Enhanced Reflexes': '强化反射',
    'Enraged Reaver': '狂怒掠夺者',
    'Entropic Incarnation': '熵之化身',
    'Equilibrium': '平衡',
    'Eroding Chains': '侵蚀锁链',
    'Erraticism': '无常',
    'Escalating Mayhem': '升级骚乱',
    'Escalation': '升级',
    'Escape Strategy': '逃生策略',
    'Escape Velocity': '逃逸速度',
    'Essence of Virtue': '美德精华',
    'Essence of the Mountain': '山脉精华',
    'Ether Flow': '以太流动',
    'Event Horizon': '事件视界',
    'Everlasting Infusions': '永恒灌注',
    'Evocational Practitioner': '唤起实践者',
    'Expendable Army': '可消耗军队',
    'Exploit': '利用',
    'Exploit the Elements': '利用元素',
    'Explosive Empowerment': '爆炸强化',
    'Exposed Wounds': '暴露伤口',
    'Exposed to the Cosmos': '暴露于宇宙',
    'Exposed to the Inferno': '暴露于炼狱',
    'Extinguishing Exhalation': '熄灭吐息',
    'Faith is a Choice': '信仰是一种选择',
    'Falcon Technique': '隼之技法',
    'Fan the Flames': '煽风点火',
    'Far Sighted': '远视',
    'Faster Ailments': '更快异常',
    'Fate Finding': '命运探寻',
    'Favourable Odds': '有利胜算',
    'Fearful Paralysis': '恐惧麻痹',
    'Feathered Fletching': '羽制箭翎',
    'Feel no Pain': '不感疼痛',
    'Fervour': '狂热',
    'Finality': '终局',
    'Finesse': '灵巧',
    'Finish Them': '了结它们',
    'Finishing Blows': '终结打击',
    'Firestarter': '点火者',
    'First Approach': '第一手段',
    'First Principle of the Hollow': '虚空第一原则',
    'First Sting': '第一刺',
    'First Teachings of the Keeper': '守护者的第一教诲',
    'Flamewalker': '踏焰者',
    'Flare': '闪光',
    'Flashy Parrying': '华丽格挡',
    'Flip the Script': '扭转局面',
    'Flow State': '心流状态',
    'Footprints in the Sand': '沙中足迹',
    'For the Jugular': '直取要害',
    'Forbidden Path': '禁忌之路',
    'Forcewave': '力量波',
    'Forthcoming': '即将来临',
    'Fortified Location': '加固位置',
    'Frantic Fighter': '狂乱斗士',
    'Frantic Reach': '狂乱触及',
    'Frantic Swings': '狂乱挥舞',
    'Frenetic': '狂热',
    'Frostwalker': '踏霜者',
    'Full Recovery': '完全恢复',
    'Full Salvo': '全面齐射',
    'Gambler': '赌徒',
    'Gathering Winds': '聚集之风',
    'Gem Enthusiast': '宝石爱好者',
    'General Electric': '电流将军',
    "General's Bindings": '将军之缚',
    'Giantslayer': '屠巨人者',
    'Gift of the Plains': '平原之礼',
    'Gigantic Following': '巨大追随',
    'Give Up Your Essence': '献出你的精华',
    'Glaciation': '冰川化',
    'Glorious Anticipation': '光荣期盼',
    'Grasping Wounds': '抓握伤口',
    'Gravedigger': '掘墓人',
    'Greatest Defence': '最强防御',
    'Grenadier': '榴弹兵',
    'Grinning Immolation': '狞笑献祭',
    'Grip of Evil': '邪恶之握',
    'Grit': '坚韧',
    'Guts': '胆量',
    'Guttural Roar': '喉音咆哮',
    'Haemorrhaging Cuts': '出血割伤',
    'Hail': '冰雹',
    'Hale Traveller': '健壮旅者',
    'Hardened Wood': '硬化木材',
    'Harsh Winter': '严冬',
    'Headshot': '爆头',
    'Heart Tissue': '心脏组织',
    'Heartbreaking': '心碎',
    'Heartstopping': '心停',
    'Heatproof': '耐热',
    'Hefty Unit': '重型单位',
    'Hidden Barb': '隐藏倒刺',
    'Hidden Forms': '隐藏形态',
    'High Alert': '高度警戒',
    'Hindered Capabilities': '受限能力',
    'Hindering Obstacles': '阻碍障碍',
    'Hollow Focus Technique': '虚空专注技法',
    'Hollow Form Technique': '虚空形态技法',
    'Hollow Resonance Technique': '虚空共鸣技法',
    'Holy Protector': '神圣守护者',
    'Honed Instincts': '磨练本能',
    'Honourless': '无荣誉',
    'Howling Beast': '嚎叫野兽',
    'Hunker Down': '蹲伏',
    'Hunter': '猎人',
    "Hunter's Talisman": '猎人的护符',
    'I am the Blizzard...': '我即是暴风雪...',
    'Ice Walls': '冰墙',
    'Icebreaker': '破冰者',
    "Ichlotl's Inferno": '伊赫洛特尔的炼狱',
    'Idolatry': '偶像崇拜',
    'Ignore Pain': '无视痛楚',
    'Illuminated Crown': '光明之冠',
    'Immaterial': '非物质',
    'Immolation': '献祭之火',
    'Immortal Thirst': '不朽之渴',
    'Impair': '削弱',
    'Impending Doom': '即将到来的末日',
    'Impenetrable Shell': '不可穿透之壳',
    'Implanted Gems': '植入宝石',
    'Incessant Cacophony': '不断嘈杂',
    'Inevitability': '必然性',
    'Inevitable Rupture': '不可避免的破裂',
    'Infernal Limit': '炼狱极限',
    'Infernalist': '地狱术士',
    'Ingenuity': '创造力',
    'Initiative': '主动性',
    'Innate Rune': '天生符文',
    'Insightfulness': '洞察力',
    'Inspiring Leader': '鼓舞领袖',
    'Instability': '不稳定',
    'Insulated Treads': '绝缘靴底',
    'Integrated Efficiency': '整合效率',
    'Intense Dose': '强效剂量',
    'Intense Flames': '强烈火焰',
    'Intricate Sigils': '复杂符文',
    'Investing Energies': '投入能量',
    'Invigorating Grandeur': '振奋宏伟',
    'Invigorating Hate': '振奋憎恨',
    'Invocated Echoes': '祈唤回响',
    'Invocated Efficiency': '祈唤效率',
    'Invocated Limit': '祈唤极限',
    'Irreparable': '不可修复',
    'Javelin': '标枪',
    "Kelari's Deception": '克拉里之欺骗',
    "Kelari's Judgment": '克拉里之审判',
    "Kelari's Malediction": '克拉里之诅咒',
    'Kept at Bay': '被阻挡在远处',
    'Killer Instinct': '杀手本能',
    'Kite Runner': '风筝跑者',
    'Knight of Chitus': '奇图斯之骑士',
    'Knight of Izaro': '伊扎罗之骑士',
    'Knight of Tarcus': '塔库斯之骑士',
    'Last Stand': '背水一战',
    "Lavianga's Brew": '拉维安加之酿造',
    'Lay Siege': '围攻',
    'Lead by Example': '以身作则',
    'Lead me through Grace...': '以恩典引导我...',
    'Leaping Ambush': '跳跃伏击',
    'Left Ventricle': '左心室',
    'Licking Wounds': '舔舐伤口',
    'Lifelong Friend': '终身挚友',
    'Lingering Horror': '挥之不去的恐怖',
    'Lingering Whispers': '挥之不去的低语',
    'Living Death': '活着的死亡',
    'Lockdown': '封锁',
    'Locked On': '锁定',
    'Lone Warrior': '孤身战士',
    'Long Distance Relationship': '远程关系',
    'Lord of Horrors': '恐怖之主',
    'Loyal Hellhound': '忠诚地狱犬',
    'Lucid Dreaming': '清醒梦',
    'Lucidity': '清醒',
    'MARAUDER': '野蛮人',
    'Madness in the Bones': '骨中疯狂',
    'Manifold Method': '多重方法',
    'Marathon Runner': '马拉松跑者',
    'Marked Agility': '标记敏捷',
    'Martial Artist': '武者',
    'Martial Artistry': '武术技艺',
    'Mass Hysteria': '群体歇斯底里',
    'Mastered Darkness': '精通黑暗',
    'Material Solidification': '物质固化',
    'Mauling Stuns': '重击眩晕',
    'Meat Recycling': '血肉回收',
    'Meditative Focus': '冥想专注',
    'Melting Flames': '熔化之焰',
    'Mental Alacrity': '心智敏捷',
    'Mental Perseverance': '心智毅力',
    'Mental Toughness': '心智坚韧',
    'Mentorship': '导师制',
    'Mind Eraser': '心灵抹消者',
    'Mind Phylacteries': '心灵命匣',
    'Mindful Awareness': '正念觉知',
    'Momentum': '动量',
    'Morning Star': '晨星',
    'Motoric Implants': '运动植入体',
    'Multiplying Squalls': '倍增暴风',
    'Multitasking': '多重任务',
    'Mutewind Agility': '静风敏捷',
    'Mystic Attunement': '秘术调和',
    'Mystic Harvest': '秘术收割',
    'Mystic Stance': '秘术姿态',
    'Natural Immunity': '自然免疫',
    "Navira's Fracturing": '纳维拉之碎裂',
    "Navira's Oasis": '纳维拉之绿洲',
    "Navira's Well": '纳维拉之井',
    'Near Sighted': '近视',
    'Necromancer': '亡灵法师',
    'Necromantic Conduit': '亡灵导管',
    'Necromantic Talisman': '亡灵护符',
    'Necrotic Touch': '坏死之触',
    'Neurological Implants': '神经植入体',
    "Night's Bite": '夜之咬',
    'No Mercy': '毫不留情',
    'Nurturing Guardian': '养育守护者',
    'Obsessive Rituals': '强迫仪式',
    'Off-Balancing Retort': '失衡反驳',
    'Open Mind': '开放思维',
    'Overexposure': '过度暴露',
    'Overwhelming Toxicity': '压倒性毒性',
    'Overzealous': '过度狂热',
    'Pack Encouragement': '集群鼓舞',
    'Paranoia': '偏执狂',
    'Passive Points': '被动技能点',
    'Passthrough Rounds': '穿透弹药',
    'Path Seeker': '寻路者',
    'Path of the Renegade': '叛徒之路',
    'Path of the Sorceress': '女术士之路',
    'Path of the Warrior': '战士之路',
    'Pathfinder': '寻路者',
    'Patient Barrier': '耐心屏障',
    'Penetrate': '穿透',
    'Perfect Opportunity': '完美时机',
    'Perfectly Placed Knife': '完美落刀',
    'Perforation': '穿孔',
    'Phased Form': '相位形态',
    'Pin their Motivation': '摧毁他们的斗志',
    'Pitiless Killer': '无情杀手',
    'Pocket Sand': '口袋沙',
    'Polish That Gear': '打磨装备',
    'Polymathy': '博学',
    'Potent Incantation': '强力咒语',
    'Powerful Casting': '强力施法',
    'Precision Salvo': '精准齐射',
    'Predatory Instinct': '掠食本能',
    'Preservation': '保存',
    'Price of Freedom': '自由的代价',
    'Primed to Explode': '准备爆炸',
    'Prize of the Hunt': '狩猎之奖',
    'Proficiency': '熟练',
    'Proliferating Weeds': '蔓延杂草',
    'Prolonged Assault': '持久突袭',
    'Protraction': '延长',
    'Psychic Fragmentation': '心灵碎片化',
    'Punctured Lung': '刺穿之肺',
    'Push the Advantage': '推进优势',
    'Pyromantic Pact': '火焰契约',
    'Quicksand Hourglass': '流沙沙漏',
    'RANGER': '游侠',
    'Rallying Form': '集结形态',
    'Rallying Icon': '集结象征',
    'Rapid Recharge': '快速充能',
    'Rattling Ball': '咔嗒球',
    'Reaving': '掠夺',
    'Redblade Discipline': '红刃纪律',
    'Refills': '补充',
    'Refocus': '重新聚焦',
    'Reinforced Rallying': '强化集结',
    'Reinvigoration': '重新振奋',
    'Repulsion': '排斥',
    'Resilient Soul': '坚韧灵魂',
    'Resolute Reach': '坚定触及',
    'Resolute Reprisal': '坚定报复',
    'Resolution': '决心',
    'Restless Dead': '不安死者',
    'Reusable Ammunition': '可重复使用的弹药',
    'Reverberation': '混响',
    'Ricochet': '弹射',
    'Right Where We Want Them': '正中下怀',
    'Ripping Blade': '撕裂之刃',
    'Ritual Cadence': '仪式节奏',
    'Ritualist': '仪式者',
    'Roil': '翻腾',
    'Rough Carapace': '粗糙甲壳',
    'Ruin': '毁灭',
    'Ruinic Helm': '符文头盔',
    'Runic Meridians': '符文经络',
    'Running Assault': '奔跑突袭',
    'Rupture the Soul': '撕裂灵魂',
    'Rupturing Pins': '撕裂定身',
    'Rusted Pins': '生锈的定身',
    'Rustle of the Leaves': '叶之沙沙',
    "Ruzhan's Reckoning": '鲁赞的清算',
    'SIX': '六号',
    'Sanguimancy': '鲜血占卜',
    'Sanguimantic Rituals': '鲜血占卜仪式',
    'Sanguine Tides': '血潮',
    'Sanguine Tolerance': '血液耐受',
    'Sap of Nightmares': '噩梦之液',
    "Saqawal's Guidance": '萨卡瓦尔的引导',
    "Saqawal's Talon": '萨卡瓦尔的利爪',
    'Savagery': '野蛮',
    'Savouring': '品味',
    'Scales of the Wyvern': '飞龙之鳞',
    'Secrets of the Orb': '能量球的秘密',
    'Seeing Stars': '眼冒金星',
    'Seething Body': '沸腾之躯',
    'Sentinels': '哨兵',
    'Serrated Edges': '锯齿边缘',
    'Shaper of Storms': '风暴塑造者',
    'Shaper of Winter': '寒冬塑造者',
    'Sharp Sight': '锐利视野',
    'Shatter Palm': '碎掌',
    'Shattering': '粉碎',
    'Shattering Blow': '粉碎打击',
    'Shedding Skin': '蜕皮',
    'Shifted Strikes': '转变打击',
    'Shimmering': '闪烁',
    'Shocking Limit': '感电极限',
    'Shockwaves': '冲击波',
    'Shrapnel': '弹片',
    'Shredding Contraptions': '粉碎装置',
    "Sic 'Em": '放狗咬他',
    'Sigil of Ice': '冰之符文',
    'Silent Guardian': '沉默守护者',
    'Singular Purpose': '唯一目标',
    'Siphon': '吸取',
    'Sitting Duck': '活靶子',
    'Sling Shots': '弹弓射击',
    'Slippery Ice': '光滑冰面',
    'Smash': '猛击',
    'Sniper': '狙击手',
    'Snowpiercer': '穿雪者',
    'Soul Bloom': '灵魂绽放',
    'Soulless Form': '无魂形态',
    'Specialised Shots': '专精射击',
    'Spellblade': '法术之刃',
    'Spike Pit': '尖刺陷阱',
    'Spiked Whip': '尖刺鞭',
    'Spiral into Depression': '螺旋陷入抑郁',
    'Spiral into Insanity': '螺旋陷入疯狂',
    'Spiral into Mania': '螺旋陷入狂热',
    'Splinters': '碎片',
    'Staggering Palm': '蹒跚掌击',
    'Staggering Wounds': '蹒跚创伤',
    'Stalking Panther': '潜行黑豹',
    'Stand Ground': '坚守阵地',
    'Stars Aligned': '星辰排列',
    'Staunching': '止血',
    'Steadfast Resolve': '坚定决心',
    'Step Like Mist': '步如薄雾',
    'Stigmata': '圣痕',
    'Stimulants': '兴奋剂',
    'Stormbreaker': '破风暴者',
    'Stormcharged': '充能风暴',
    'Stormwalker': '踏风暴者',
    'Stormweaver': '风暴编织者',
    'Strategic Embankments': '战略壁垒',
    'Strong Chin': '坚毅下颚',
    'Struck Through': '击穿',
    'Stupefy': '愚钝',
    'Sturdy Metal': '坚固金属',
    'Sturdy Mind': '坚固思维',
    'Stylebender': '风格扭曲者',
    'Subterfuge Mask': '诡计面具',
    'Succour': '救助',
    'Sudden Escalation': '突然升级',
    'Sudden Infuriation': '突然暴怒',
    'Suffusion': '弥漫',
    'Sundering': '破甲',
    'Supportive Ancestors': '支持先祖',
    'Surging Avatar': '涌动化身',
    'Surging Beast': '涌动野兽',
    'Sustainable Practices': '可持续实践',
    'Symbol of Defiance': '挑衅之象征',
    'TEMPLAR': '圣堂武士',
    'Tactical Retreat': '战术撤退',
    'Tactician': '战术家',
    'Tempered Mind': '淬炼心智',
    'Tempest Caller': '暴风召唤者',
    'Tenfold Attacks': '十倍攻击',
    "The Catha's Balance": '卡萨的平衡',
    'The Fabled Stag': '传说中的雄鹿',
    'The Fourth Teaching': '第四教诲',
    'The Great Boar': '巨野猪',
    'The Hollowkeeper': '虚空守护者',
    'The Howling Primate': '嚎叫灵长类',
    'The Lesser Harm': '较小伤害',
    "The Mhacha's Gift": '玛哈的赠礼',
    'The Natural Order': '自然秩序',
    'The Soul Meridian': '灵魂经络',
    'The Spring Hare': '春之野兔',
    'The Winter Owl': '冬之枭',
    'Thickened Arteries': '增厚动脉',
    'Thicket Warding': '灌木防护',
    'Thin Ice': '薄冰',
    'Thornhide': '荆棘兽皮',
    'Thousand Cuts': '千刀万剐',
    'Thrill of Battle': '战斗快感',
    'Thrill of the Fight': '战斗快感',
    'Thrilling Chase': '刺激追逐',
    'Thunderstruck': '雷击',
    'Tides of Change': '变革之潮',
    "Titan's Determination": '泰坦的决心',
    'Tolerant Equipment': '耐受装备',
    'Total Incineration': '彻底焚化',
    'Toxic Sludge': '毒泥',
    'Toxic Tolerance': '毒素耐受',
    "Traveller's Wisdom": '旅者的智慧',
    'Trusted Kinship': '信赖血缘',
    "Tukohama's Brew": '图克哈玛的酿造',
    'Turn the Clock Back': '倒流时光',
    'Turn the Clock Forward': '快进时光',
    'Unbending': '不屈',
    'Unbound Encore': '无拘重演',
    'Unbound Forces': '无拘之力',
    'Unbreaking': '不破',
    'Unexpected Finesse': '意外灵巧',
    'Unforgiving': '不饶恕',
    'Unfurled Finger': '展开之指',
    'Unhindered': '不受阻碍',
    'Unimpeded': '畅通无阻',
    'Unleash Hell!': '释放地狱！',
    'Unnatural Resilience': '非自然韧性',
    'Unravelling': '瓦解',
    'Unsight': '无视',
    'Unspoken Bond': '无言羁绊',
    'Unstable Bond': '不稳定羁绊',
    'Unstoppable Barrier': '不可阻挡的屏障',
    'Unyielding': '不屈不挠',
    'Urgent Call': '紧急召唤',
    'Utility Ordnance': '实用军械',
    'Vale Dweller': '山谷居民',
    'Vale Shelter': '山谷庇护',
    "Varashta's Intuition": '瓦拉斯塔的直觉',
    'Vengeance': '复仇',
    'Versatile Arms': '多才武器',
    'Viciousness': '恶毒',
    'Vigilance': '警戒',
    'Vigorous Remnants': '活力残留',
    'Vitality Siphon': '活力吸取',
    'Vivid Stampede': '生动的狂奔',
    'Vocal Empowerment': '声音赋权',
    'Volatile Catalyst': '不稳定催化剂',
    'Volatile Grenades': '不稳定手雷',
    'Volcanic Skin': '火山皮肤',
    "Voll's Protection": '沃尔之保护',
    'Voracious': '贪婪',
    'Vulgar Methods': '粗俗手段',
    'WITCH': '女巫',
    'Waking Dream': '醒梦',
    'Waning Hindrances': '消退障碍',
    'Warding Fetish': '护身符',
    'Warding Potions': '防护药剂',
    'Warlord Berserker': '军阀狂战士',
    'Warlord Leader': '军阀领袖',
    'Warm the Heart': '温暖心灵',
    'Wary Dodging': '谨慎闪避',
    'Wasting': '消逝',
    'Wasting Casts': '消逝施法',
    'Way of the Mountain': '山之道',
    'Way of the Stonefist': '石拳之道',
    'Wellspring': '源泉',
    'Whirling Assault': '旋风突袭',
    'Whoever Pays Best': '价高者得',
    'Widespread Coverage': '广泛覆盖',
    'Wildsurge Incantation': '狂野涌动咒语',
    'Wildwood Persistence': '荒野坚持',
    'Witchbane': '女巫克星',
    'Witchhunter': '猎巫者',
    'Woodland Aspect': '林地面貌',
    "Wyvern's Breath": '飞龙吐息',
    'Zealous Inquisition': '狂热审判',
    'Zone of Control': '控制区域',
}
